// Client lifecycle: design steps + checklists, run a client through them.
const { instrument, launch, newPage, check, report, OUT } = require('./common.js');
(async () => {
  instrument(process.argv[2], OUT+'/lc.html');
  const b = await launch();
  const p = await newPage(b, OUT+'/lc.html', {business:{pipeline:[], clients:[{id:'c1', name:'Nina', business:'Nina Co', status:'active', mrr:2000, touches:[], deliverables:[], journal:[]}], packages:[]}});
  const E = (code) => p.evaluate(c => window.__op.ev(c), code);
  check('existing client kept in Active', (await E("state.business.clients[0].stage"))==='active');
  check('default checklists seeded', (await E("crmStage('client','onboarding').checklist.length"))===5);
  await p.click('[data-action="nav"][data-view="business"]'); await p.click('[data-action="businessTab"][data-tab="clients"]');
  await p.click('[data-action="openLifecycleEditor"]');
  check('lifecycle editor open', await p.isVisible('#lifecycleOverlay:not(.hidden) .lc-editor'));
  await p.fill('#newStage-client', 'Kickoff call'); await p.press('#newStage-client', 'Enter');
  const order = await E("crmStages('client').map(s=>s.label).join(' > ')");
  check('new step at end of active path', order==='Onboarding > Active > At risk > Kickoff call > Paused > Churned', order);
  const kid = await E("crmStages('client').find(s=>s.label==='Kickoff call').id");
  await p.click('[data-action="moveStage"][data-id="'+kid+'"][data-dir="-1"]');
  await p.click('[data-action="moveStage"][data-id="'+kid+'"][data-dir="-1"]');
  check('reordered: Onboarding > Kickoff call > Active', (await E("crmStages('client').map(s=>s.label).slice(0,3).join(' > ')"))==='Onboarding > Kickoff call > Active');
  await p.fill('#lcNewItem-'+kid, 'Send agenda'); await p.press('#lcNewItem-'+kid, 'Enter');
  await p.fill('#lcNewItem-'+kid, 'Record the call'); await p.press('#lcNewItem-'+kid, 'Enter');
  check('checklist items added via Enter', (await E("crmStage('client','"+kid+"').checklist.map(i=>i.text).join('|')"))==='Send agenda|Record the call');
  await p.fill('[data-lc-item="onboarding:lconboarding0"]', 'Send welcome video'); await p.press('[data-lc-item="onboarding:lconboarding0"]', 'Tab');
  check('item renamed', (await E("crmStage('client','onboarding').checklist[0].text"))==='Send welcome video');
  await p.click('[data-action="closeLifecycleEditor"]');
  // new client lands on step 1 with its checklist
  await p.click('[data-action="openNewContact"][data-kind="client"]');
  await p.fill('#ncName','Zed'); await p.fill('#ncCompany','Zed Media'); await p.click('[data-action="saveNewContact"]');
  check('new client opens on Onboarding checklist', await p.isVisible('#clientModalOverlay:not(.hidden) .lc-card') && (await p.textContent('.lc-now-title'))==='Onboarding');
  const zid = await E("state.business.clients.find(c=>c.business==='Zed Media').id");
  await p.check('[data-lc-check="'+zid+':onboarding:lconboarding0"]');
  await p.check('[data-lc-check="'+zid+':onboarding:lconboarding1"]');
  check('progress 2/5', (await p.textContent('.lc-now')).includes('2 / 5'));
  await p.click('#clientModalContent [data-action="lcToTasks"]');
  const tasks = await E("state.tasks.items.filter(t=>t.lifecycleRef && t.lifecycleRef.startsWith('"+zid+"')).map(t=>t.title)");
  check('remaining 3 items sent to tasks', tasks.length===3 && tasks[0].includes('Zed Media'), tasks);
  await E("const t=state.tasks.items.find(t=>t.lifecycleRef==='"+zid+":onboarding:lconboarding2'); t.status='done'; t.completedAt=todayStr(); renderView();");
  check('finishing the task checks the item (3/5)', (await p.textContent('.lc-now')).includes('3 / 5'));
  await p.check('[data-lc-check="'+zid+':onboarding:lconboarding3"]'); await p.check('[data-lc-check="'+zid+':onboarding:lconboarding4"]');
  check('all done → next step highlighted', await p.isVisible('.lc-next-ready'));
  await p.click('.lc-next-ready');
  check('moved to Kickoff call', (await E("crmStage('client', state.business.clients.find(c=>c.id==='"+zid+"').stage).label"))==='Kickoff call' && (await p.textContent('.lc-now-title'))==='Kickoff call');
  check('timeline records it', (await E("state.business.clients.find(c=>c.id==='"+zid+"').timeline.some(t=>t.text==='Onboarding → Kickoff call')")));
  await p.click('[data-action="closeClientModalAndSave"]');
  check('board card shows progress', await p.isVisible('.crm-card[data-key="crm-'+zid+'"] .lc-badge'));
  // Today: client next steps
  await p.click('[data-action="nav"][data-view="today"]');
  check('Client Next Steps on Today', await p.isVisible('.lc-steps-card[data-key="lcs-'+zid+'"]'));
  await p.check('.lc-steps-card[data-key="lcs-'+zid+'"] input[data-lc-check]');
  check('check from Today', (await E("state.business.clients.find(c=>c.id==='"+zid+"').lifecycle.checks['"+kid+"'].length"))===1);
  await p.screenshot({path:OUT+'/lc-today.png'});
  await p.click('[data-action="nav"][data-view="business"]'); await p.click('[data-action="businessTab"][data-tab="clients"]');
  await p.click('.crm-card[data-key="crm-'+zid+'"] .crm-card-main');
  await p.screenshot({path:OUT+'/lc-client.png'});
  await p.click('[data-action="closeClientModalAndSave"]');
  await p.click('[data-action="openLifecycleEditor"]');
  await p.screenshot({path:OUT+'/lc-editor.png'});
  check('saved across reload', true);
  await p.reload(); await p.waitForTimeout(400);
  check('steps persist after reload', (await E("crmStages('client').map(s=>s.label).slice(0,2).join(' > ')"))==='Onboarding > Kickoff call');
  check('no page errors', p.errors.length===0, p.errors);
  await b.close();
  process.exit(report()?1:0);
})();
